/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package officeolympics;

import static javafx.application.Application.launch;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;
import officeolympics.front.navigation.Flow;
import officeolympics.front.scenes.SceneLoader;
import officeolympics.front.scenes.Scenes;

public class Main extends Application {
    private static Stage stage;

    public static Stage getStage() {
        return stage;
    }

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage_) {
        stage = stage_;

        Scenes.MainScreenScene = SceneLoader.load("MainScreenScene.fxml");

        Flow.add(Scenes.MainScreenScene);

        stage.setResizable(true);
        stage.setTitle("FUMA");
        stage.setScene(Scenes.MainScreenScene);
        stage.show();
    }

    public static void setScene(Scene scene) {
        stage.setScene(scene);
    }
}
